### ISSUE TITLE
Symlinks cause gitbom to fail

### ISSUE THREAD

**Issue by imjasonh** [fkautz/gitbom-go#5]
Repro:
- clone https://gist.github.com/imjasonh/ec33937f32ab17c36cdd50c2ea23c1d7 or make any directory containing a few simple files
- `gitbom *` succeeds
- `ln -s new.txt new.symlink`
- `gitbom *`
- observe:

```
2022/02/10 16:09:46 main.go:16: actual reader length did not match expected length
```

**Comment by fkautz** [comment]
Should be fixed with #6. Please reopen if it's still an issue.
